/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/appscode/stash/apis/stash/v1alpha2"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AgentTemplateLister helps list AgentTemplates.
type AgentTemplateLister interface {
	// List lists all AgentTemplates in the indexer.
	List(selector labels.Selector) (ret []*v1alpha2.AgentTemplate, err error)
	// Get retrieves the AgentTemplate from the index for a given name.
	Get(name string) (*v1alpha2.AgentTemplate, error)
	AgentTemplateListerExpansion
}

// agentTemplateLister implements the AgentTemplateLister interface.
type agentTemplateLister struct {
	indexer cache.Indexer
}

// NewAgentTemplateLister returns a new AgentTemplateLister.
func NewAgentTemplateLister(indexer cache.Indexer) AgentTemplateLister {
	return &agentTemplateLister{indexer: indexer}
}

// List lists all AgentTemplates in the indexer.
func (s *agentTemplateLister) List(selector labels.Selector) (ret []*v1alpha2.AgentTemplate, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.AgentTemplate))
	})
	return ret, err
}

// Get retrieves the AgentTemplate from the index for a given name.
func (s *agentTemplateLister) Get(name string) (*v1alpha2.AgentTemplate, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("agenttemplate"), name)
	}
	return obj.(*v1alpha2.AgentTemplate), nil
}
