/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// ActionListerExpansion allows custom methods to be added to
// ActionLister.
type ActionListerExpansion interface{}

// BackupConfigurationListerExpansion allows custom methods to be added to
// BackupConfigurationLister.
type BackupConfigurationListerExpansion interface{}

// BackupConfigurationNamespaceListerExpansion allows custom methods to be added to
// BackupConfigurationNamespaceLister.
type BackupConfigurationNamespaceListerExpansion interface{}

// BackupInstanceListerExpansion allows custom methods to be added to
// BackupInstanceLister.
type BackupInstanceListerExpansion interface{}

// BackupInstanceNamespaceListerExpansion allows custom methods to be added to
// BackupInstanceNamespaceLister.
type BackupInstanceNamespaceListerExpansion interface{}

// DefaultBackupConfigurationListerExpansion allows custom methods to be added to
// DefaultBackupConfigurationLister.
type DefaultBackupConfigurationListerExpansion interface{}

// RecoveryListerExpansion allows custom methods to be added to
// RecoveryLister.
type RecoveryListerExpansion interface{}

// RecoveryNamespaceListerExpansion allows custom methods to be added to
// RecoveryNamespaceLister.
type RecoveryNamespaceListerExpansion interface{}

// RepositoryListerExpansion allows custom methods to be added to
// RepositoryLister.
type RepositoryListerExpansion interface{}

// RepositoryNamespaceListerExpansion allows custom methods to be added to
// RepositoryNamespaceLister.
type RepositoryNamespaceListerExpansion interface{}

// StashTemplateListerExpansion allows custom methods to be added to
// StashTemplateLister.
type StashTemplateListerExpansion interface{}
