/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/appscode/stash/apis/stash/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStashTemplates implements StashTemplateInterface
type FakeStashTemplates struct {
	Fake *FakeStashV1alpha2
}

var stashtemplatesResource = schema.GroupVersionResource{Group: "stash.appscode.com", Version: "v1alpha2", Resource: "stashtemplates"}

var stashtemplatesKind = schema.GroupVersionKind{Group: "stash.appscode.com", Version: "v1alpha2", Kind: "StashTemplate"}

// Get takes name of the stashTemplate, and returns the corresponding stashTemplate object, and an error if there is any.
func (c *FakeStashTemplates) Get(name string, options v1.GetOptions) (result *v1alpha2.StashTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(stashtemplatesResource, name), &v1alpha2.StashTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.StashTemplate), err
}

// List takes label and field selectors, and returns the list of StashTemplates that match those selectors.
func (c *FakeStashTemplates) List(opts v1.ListOptions) (result *v1alpha2.StashTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(stashtemplatesResource, stashtemplatesKind, opts), &v1alpha2.StashTemplateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.StashTemplateList{ListMeta: obj.(*v1alpha2.StashTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha2.StashTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested stashTemplates.
func (c *FakeStashTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(stashtemplatesResource, opts))
}

// Create takes the representation of a stashTemplate and creates it.  Returns the server's representation of the stashTemplate, and an error, if there is any.
func (c *FakeStashTemplates) Create(stashTemplate *v1alpha2.StashTemplate) (result *v1alpha2.StashTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(stashtemplatesResource, stashTemplate), &v1alpha2.StashTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.StashTemplate), err
}

// Update takes the representation of a stashTemplate and updates it. Returns the server's representation of the stashTemplate, and an error, if there is any.
func (c *FakeStashTemplates) Update(stashTemplate *v1alpha2.StashTemplate) (result *v1alpha2.StashTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(stashtemplatesResource, stashTemplate), &v1alpha2.StashTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.StashTemplate), err
}

// Delete takes name of the stashTemplate and deletes it. Returns an error if one occurs.
func (c *FakeStashTemplates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(stashtemplatesResource, name), &v1alpha2.StashTemplate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStashTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(stashtemplatesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.StashTemplateList{})
	return err
}

// Patch applies the patch and returns the patched stashTemplate.
func (c *FakeStashTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.StashTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(stashtemplatesResource, name, data, subresources...), &v1alpha2.StashTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.StashTemplate), err
}
