/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/appscode/stash/apis/stash/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackupInstances implements BackupInstanceInterface
type FakeBackupInstances struct {
	Fake *FakeStashV1alpha2
	ns   string
}

var backupinstancesResource = schema.GroupVersionResource{Group: "stash.appscode.com", Version: "v1alpha2", Resource: "backupinstances"}

var backupinstancesKind = schema.GroupVersionKind{Group: "stash.appscode.com", Version: "v1alpha2", Kind: "BackupInstance"}

// Get takes name of the backupInstance, and returns the corresponding backupInstance object, and an error if there is any.
func (c *FakeBackupInstances) Get(name string, options v1.GetOptions) (result *v1alpha2.BackupInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(backupinstancesResource, c.ns, name), &v1alpha2.BackupInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.BackupInstance), err
}

// List takes label and field selectors, and returns the list of BackupInstances that match those selectors.
func (c *FakeBackupInstances) List(opts v1.ListOptions) (result *v1alpha2.BackupInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(backupinstancesResource, backupinstancesKind, c.ns, opts), &v1alpha2.BackupInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.BackupInstanceList{ListMeta: obj.(*v1alpha2.BackupInstanceList).ListMeta}
	for _, item := range obj.(*v1alpha2.BackupInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backupInstances.
func (c *FakeBackupInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(backupinstancesResource, c.ns, opts))

}

// Create takes the representation of a backupInstance and creates it.  Returns the server's representation of the backupInstance, and an error, if there is any.
func (c *FakeBackupInstances) Create(backupInstance *v1alpha2.BackupInstance) (result *v1alpha2.BackupInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(backupinstancesResource, c.ns, backupInstance), &v1alpha2.BackupInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.BackupInstance), err
}

// Update takes the representation of a backupInstance and updates it. Returns the server's representation of the backupInstance, and an error, if there is any.
func (c *FakeBackupInstances) Update(backupInstance *v1alpha2.BackupInstance) (result *v1alpha2.BackupInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(backupinstancesResource, c.ns, backupInstance), &v1alpha2.BackupInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.BackupInstance), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBackupInstances) UpdateStatus(backupInstance *v1alpha2.BackupInstance) (*v1alpha2.BackupInstance, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(backupinstancesResource, "status", c.ns, backupInstance), &v1alpha2.BackupInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.BackupInstance), err
}

// Delete takes name of the backupInstance and deletes it. Returns an error if one occurs.
func (c *FakeBackupInstances) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(backupinstancesResource, c.ns, name), &v1alpha2.BackupInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackupInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(backupinstancesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.BackupInstanceList{})
	return err
}

// Patch applies the patch and returns the patched backupInstance.
func (c *FakeBackupInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.BackupInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(backupinstancesResource, c.ns, name, data, subresources...), &v1alpha2.BackupInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.BackupInstance), err
}
