/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/appscode/stash/apis/stash/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDefaultBackupConfigurations implements DefaultBackupConfigurationInterface
type FakeDefaultBackupConfigurations struct {
	Fake *FakeStashV1alpha2
}

var defaultbackupconfigurationsResource = schema.GroupVersionResource{Group: "stash.appscode.com", Version: "v1alpha2", Resource: "defaultbackupconfigurations"}

var defaultbackupconfigurationsKind = schema.GroupVersionKind{Group: "stash.appscode.com", Version: "v1alpha2", Kind: "DefaultBackupConfiguration"}

// Get takes name of the defaultBackupConfiguration, and returns the corresponding defaultBackupConfiguration object, and an error if there is any.
func (c *FakeDefaultBackupConfigurations) Get(name string, options v1.GetOptions) (result *v1alpha2.DefaultBackupConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(defaultbackupconfigurationsResource, name), &v1alpha2.DefaultBackupConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.DefaultBackupConfiguration), err
}

// List takes label and field selectors, and returns the list of DefaultBackupConfigurations that match those selectors.
func (c *FakeDefaultBackupConfigurations) List(opts v1.ListOptions) (result *v1alpha2.DefaultBackupConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(defaultbackupconfigurationsResource, defaultbackupconfigurationsKind, opts), &v1alpha2.DefaultBackupConfigurationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.DefaultBackupConfigurationList{ListMeta: obj.(*v1alpha2.DefaultBackupConfigurationList).ListMeta}
	for _, item := range obj.(*v1alpha2.DefaultBackupConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested defaultBackupConfigurations.
func (c *FakeDefaultBackupConfigurations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(defaultbackupconfigurationsResource, opts))
}

// Create takes the representation of a defaultBackupConfiguration and creates it.  Returns the server's representation of the defaultBackupConfiguration, and an error, if there is any.
func (c *FakeDefaultBackupConfigurations) Create(defaultBackupConfiguration *v1alpha2.DefaultBackupConfiguration) (result *v1alpha2.DefaultBackupConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(defaultbackupconfigurationsResource, defaultBackupConfiguration), &v1alpha2.DefaultBackupConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.DefaultBackupConfiguration), err
}

// Update takes the representation of a defaultBackupConfiguration and updates it. Returns the server's representation of the defaultBackupConfiguration, and an error, if there is any.
func (c *FakeDefaultBackupConfigurations) Update(defaultBackupConfiguration *v1alpha2.DefaultBackupConfiguration) (result *v1alpha2.DefaultBackupConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(defaultbackupconfigurationsResource, defaultBackupConfiguration), &v1alpha2.DefaultBackupConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.DefaultBackupConfiguration), err
}

// Delete takes name of the defaultBackupConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeDefaultBackupConfigurations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(defaultbackupconfigurationsResource, name), &v1alpha2.DefaultBackupConfiguration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDefaultBackupConfigurations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(defaultbackupconfigurationsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.DefaultBackupConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched defaultBackupConfiguration.
func (c *FakeDefaultBackupConfigurations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.DefaultBackupConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(defaultbackupconfigurationsResource, name, data, subresources...), &v1alpha2.DefaultBackupConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.DefaultBackupConfiguration), err
}
