/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/appscode/stash/apis/stash/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAgentTemplates implements AgentTemplateInterface
type FakeAgentTemplates struct {
	Fake *FakeStashV1alpha2
}

var agenttemplatesResource = schema.GroupVersionResource{Group: "stash.appscode.com", Version: "v1alpha2", Resource: "agenttemplates"}

var agenttemplatesKind = schema.GroupVersionKind{Group: "stash.appscode.com", Version: "v1alpha2", Kind: "AgentTemplate"}

// Get takes name of the agentTemplate, and returns the corresponding agentTemplate object, and an error if there is any.
func (c *FakeAgentTemplates) Get(name string, options v1.GetOptions) (result *v1alpha2.AgentTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(agenttemplatesResource, name), &v1alpha2.AgentTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.AgentTemplate), err
}

// List takes label and field selectors, and returns the list of AgentTemplates that match those selectors.
func (c *FakeAgentTemplates) List(opts v1.ListOptions) (result *v1alpha2.AgentTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(agenttemplatesResource, agenttemplatesKind, opts), &v1alpha2.AgentTemplateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.AgentTemplateList{ListMeta: obj.(*v1alpha2.AgentTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha2.AgentTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested agentTemplates.
func (c *FakeAgentTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(agenttemplatesResource, opts))
}

// Create takes the representation of a agentTemplate and creates it.  Returns the server's representation of the agentTemplate, and an error, if there is any.
func (c *FakeAgentTemplates) Create(agentTemplate *v1alpha2.AgentTemplate) (result *v1alpha2.AgentTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(agenttemplatesResource, agentTemplate), &v1alpha2.AgentTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.AgentTemplate), err
}

// Update takes the representation of a agentTemplate and updates it. Returns the server's representation of the agentTemplate, and an error, if there is any.
func (c *FakeAgentTemplates) Update(agentTemplate *v1alpha2.AgentTemplate) (result *v1alpha2.AgentTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(agenttemplatesResource, agentTemplate), &v1alpha2.AgentTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.AgentTemplate), err
}

// Delete takes name of the agentTemplate and deletes it. Returns an error if one occurs.
func (c *FakeAgentTemplates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(agenttemplatesResource, name), &v1alpha2.AgentTemplate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAgentTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(agenttemplatesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.AgentTemplateList{})
	return err
}

// Patch applies the patch and returns the patched agentTemplate.
func (c *FakeAgentTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.AgentTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(agenttemplatesResource, name, data, subresources...), &v1alpha2.AgentTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.AgentTemplate), err
}
