/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/appscode/stash/apis/stash/v1alpha2"
	scheme "github.com/appscode/stash/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ActionsGetter has a method to return a ActionInterface.
// A group's client should implement this interface.
type ActionsGetter interface {
	Actions() ActionInterface
}

// ActionInterface has methods to work with Action resources.
type ActionInterface interface {
	Create(*v1alpha2.Action) (*v1alpha2.Action, error)
	Update(*v1alpha2.Action) (*v1alpha2.Action, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.Action, error)
	List(opts v1.ListOptions) (*v1alpha2.ActionList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.Action, err error)
	ActionExpansion
}

// actions implements ActionInterface
type actions struct {
	client rest.Interface
}

// newActions returns a Actions
func newActions(c *StashV1alpha2Client) *actions {
	return &actions{
		client: c.RESTClient(),
	}
}

// Get takes name of the action, and returns the corresponding action object, and an error if there is any.
func (c *actions) Get(name string, options v1.GetOptions) (result *v1alpha2.Action, err error) {
	result = &v1alpha2.Action{}
	err = c.client.Get().
		Resource("actions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Actions that match those selectors.
func (c *actions) List(opts v1.ListOptions) (result *v1alpha2.ActionList, err error) {
	result = &v1alpha2.ActionList{}
	err = c.client.Get().
		Resource("actions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested actions.
func (c *actions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("actions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a action and creates it.  Returns the server's representation of the action, and an error, if there is any.
func (c *actions) Create(action *v1alpha2.Action) (result *v1alpha2.Action, err error) {
	result = &v1alpha2.Action{}
	err = c.client.Post().
		Resource("actions").
		Body(action).
		Do().
		Into(result)
	return
}

// Update takes the representation of a action and updates it. Returns the server's representation of the action, and an error, if there is any.
func (c *actions) Update(action *v1alpha2.Action) (result *v1alpha2.Action, err error) {
	result = &v1alpha2.Action{}
	err = c.client.Put().
		Resource("actions").
		Name(action.Name).
		Body(action).
		Do().
		Into(result)
	return
}

// Delete takes name of the action and deletes it. Returns an error if one occurs.
func (c *actions) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("actions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *actions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("actions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched action.
func (c *actions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.Action, err error) {
	result = &v1alpha2.Action{}
	err = c.client.Patch(pt).
		Resource("actions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
