/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/appscode/stash/apis/stash/v1alpha2"
	scheme "github.com/appscode/stash/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BackupInstancesGetter has a method to return a BackupInstanceInterface.
// A group's client should implement this interface.
type BackupInstancesGetter interface {
	BackupInstances(namespace string) BackupInstanceInterface
}

// BackupInstanceInterface has methods to work with BackupInstance resources.
type BackupInstanceInterface interface {
	Create(*v1alpha2.BackupInstance) (*v1alpha2.BackupInstance, error)
	Update(*v1alpha2.BackupInstance) (*v1alpha2.BackupInstance, error)
	UpdateStatus(*v1alpha2.BackupInstance) (*v1alpha2.BackupInstance, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.BackupInstance, error)
	List(opts v1.ListOptions) (*v1alpha2.BackupInstanceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.BackupInstance, err error)
	BackupInstanceExpansion
}

// backupInstances implements BackupInstanceInterface
type backupInstances struct {
	client rest.Interface
	ns     string
}

// newBackupInstances returns a BackupInstances
func newBackupInstances(c *StashV1alpha2Client, namespace string) *backupInstances {
	return &backupInstances{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the backupInstance, and returns the corresponding backupInstance object, and an error if there is any.
func (c *backupInstances) Get(name string, options v1.GetOptions) (result *v1alpha2.BackupInstance, err error) {
	result = &v1alpha2.BackupInstance{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backupinstances").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BackupInstances that match those selectors.
func (c *backupInstances) List(opts v1.ListOptions) (result *v1alpha2.BackupInstanceList, err error) {
	result = &v1alpha2.BackupInstanceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backupinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested backupInstances.
func (c *backupInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("backupinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a backupInstance and creates it.  Returns the server's representation of the backupInstance, and an error, if there is any.
func (c *backupInstances) Create(backupInstance *v1alpha2.BackupInstance) (result *v1alpha2.BackupInstance, err error) {
	result = &v1alpha2.BackupInstance{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("backupinstances").
		Body(backupInstance).
		Do().
		Into(result)
	return
}

// Update takes the representation of a backupInstance and updates it. Returns the server's representation of the backupInstance, and an error, if there is any.
func (c *backupInstances) Update(backupInstance *v1alpha2.BackupInstance) (result *v1alpha2.BackupInstance, err error) {
	result = &v1alpha2.BackupInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backupinstances").
		Name(backupInstance.Name).
		Body(backupInstance).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *backupInstances) UpdateStatus(backupInstance *v1alpha2.BackupInstance) (result *v1alpha2.BackupInstance, err error) {
	result = &v1alpha2.BackupInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backupinstances").
		Name(backupInstance.Name).
		SubResource("status").
		Body(backupInstance).
		Do().
		Into(result)
	return
}

// Delete takes name of the backupInstance and deletes it. Returns an error if one occurs.
func (c *backupInstances) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backupinstances").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *backupInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backupinstances").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched backupInstance.
func (c *backupInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.BackupInstance, err error) {
	result = &v1alpha2.BackupInstance{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("backupinstances").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
