/*
Copyright 2019 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/appscode/stash/apis/stash/v1alpha2"
	scheme "github.com/appscode/stash/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StashTemplatesGetter has a method to return a StashTemplateInterface.
// A group's client should implement this interface.
type StashTemplatesGetter interface {
	StashTemplates() StashTemplateInterface
}

// StashTemplateInterface has methods to work with StashTemplate resources.
type StashTemplateInterface interface {
	Create(*v1alpha2.StashTemplate) (*v1alpha2.StashTemplate, error)
	Update(*v1alpha2.StashTemplate) (*v1alpha2.StashTemplate, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.StashTemplate, error)
	List(opts v1.ListOptions) (*v1alpha2.StashTemplateList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.StashTemplate, err error)
	StashTemplateExpansion
}

// stashTemplates implements StashTemplateInterface
type stashTemplates struct {
	client rest.Interface
}

// newStashTemplates returns a StashTemplates
func newStashTemplates(c *StashV1alpha2Client) *stashTemplates {
	return &stashTemplates{
		client: c.RESTClient(),
	}
}

// Get takes name of the stashTemplate, and returns the corresponding stashTemplate object, and an error if there is any.
func (c *stashTemplates) Get(name string, options v1.GetOptions) (result *v1alpha2.StashTemplate, err error) {
	result = &v1alpha2.StashTemplate{}
	err = c.client.Get().
		Resource("stashtemplates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StashTemplates that match those selectors.
func (c *stashTemplates) List(opts v1.ListOptions) (result *v1alpha2.StashTemplateList, err error) {
	result = &v1alpha2.StashTemplateList{}
	err = c.client.Get().
		Resource("stashtemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested stashTemplates.
func (c *stashTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("stashtemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a stashTemplate and creates it.  Returns the server's representation of the stashTemplate, and an error, if there is any.
func (c *stashTemplates) Create(stashTemplate *v1alpha2.StashTemplate) (result *v1alpha2.StashTemplate, err error) {
	result = &v1alpha2.StashTemplate{}
	err = c.client.Post().
		Resource("stashtemplates").
		Body(stashTemplate).
		Do().
		Into(result)
	return
}

// Update takes the representation of a stashTemplate and updates it. Returns the server's representation of the stashTemplate, and an error, if there is any.
func (c *stashTemplates) Update(stashTemplate *v1alpha2.StashTemplate) (result *v1alpha2.StashTemplate, err error) {
	result = &v1alpha2.StashTemplate{}
	err = c.client.Put().
		Resource("stashtemplates").
		Name(stashTemplate.Name).
		Body(stashTemplate).
		Do().
		Into(result)
	return
}

// Delete takes name of the stashTemplate and deletes it. Returns an error if one occurs.
func (c *stashTemplates) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("stashtemplates").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *stashTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("stashtemplates").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched stashTemplate.
func (c *stashTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.StashTemplate, err error) {
	result = &v1alpha2.StashTemplate{}
	err = c.client.Patch(pt).
		Resource("stashtemplates").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
