apiVersion: stash.appscode.com/v1alpha2
kind: Recovery
metadata:
  name: recovery-database-demo
  namespace: demo
spec:
  repository:
    name: stash-backup-repo
    namespace: demo
  # stashTemplate indicates StashTemplate crd to use for creating recovery job
  stashTemplate: pgRecovery
  recoverTo:
    # indicates the respective AppBinding crd for target database that we want to initialize from backup
    workload:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: quick-postgres
